"""
Django settings for allewatcher project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '56&twh8quk=)zw$w#^gv=ybyyr4r0d08in$bmt_yealpg=uv(r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    # django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # packages apps
    'captcha',
    'crispy_forms',
    # project apps
    'search',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'allewatcher.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['../allewatcher/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'allewatcher.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # false let me to compare dates in main.py Run().check()


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

EXTERNAL_LIBS_PATH = os.path.join(PROJECT_PATH, 'externals', 'libs')
EXTERNAL_APPS_PATH = os.path.join(PROJECT_PATH, 'externals', 'apps')
sys.path = ["", EXTERNAL_APPS_PATH, EXTERNAL_LIBS_PATH] + sys.path
STATIC_ROOT = os.path.join(PROJECT_PATH, 'allewatcher', 'static')
MEDIA_ROOT = os.path.join(PROJECT_PATH, 'allewatcher', 'media')
STATICFILES_DIRS = (os.path.join(PROJECT_PATH, 'static'),)
LOCALE_PATHS = (os.path.join(PROJECT_PATH, 'allewatcher', 'locale'),)
FILE_UPLOAD_TEMP_DIR = os.path.join(PROJECT_PATH, 'tmp')

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'allewatcher@gmail.com'
EMAIL_HOST_PASSWORD = 'blacharska1'  # have to delete this before put on github
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'allewatcher@gmail.com'

CRISPY_TEMPLATE_PACK = 'bootstrap3'
